spring.application.name=learningSpringBootApp


payment.provider=razorpay


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=muskanmittal
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api